# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-02-13 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
                ('description', models.CharField(max_length=200)),
                ('duration', models.DateTimeField(auto_now_add=True)),
                ('avtar', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
                ('description', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectsApp.Project')),
            ],
            options={
                'verbose_name_plural': 'tasks',
            },
        ),
    ]
